### ISSUE TITLE
missing last tick mark and tick text of x-axis and y-axis

### ISSUE THREAD

**Issue by cjiang-ibm** [Brunel-Visualization/Brunel#135] opened 2016-08-24 19:00 UTC
Here is the syntax I was using:

line x(falsePositiveRate:[0,1]:linear) y(truePositiveRate:[0,1])  + point x(falsePositiveRate:[0,1]:linear) y(truePositiveRate:[0,1]) size(falsePositiveRate:[50, 50])  tooltip(#all) rectangular(aspect:1, square)  interaction(panzoom)  axes(x:'False positive rate(1-specificity)':grid, y:'True positive rate (sensitivity)':grid) style('.inner {stroke:#e0e0e0; stroke-width:1px} .axis.x .title {label-location:left; font-size:14px;  padding-bottom:5px} .axis.x .tick text{fill:#e0e0e0; font-size:12px; padding-bottom:15px; padding-top: 5px} .axis .tick line{size:8px; stroke-width:1px} .axis.y .tick text{ fill:#e0e0e0; font-size:12px; padding-right: 5px; padding-left: 15px}  .axis.y .title {label-location:left; padding-left:5px; font-size:14px}  .element.point {fill: #41D6C3; stroke-width: 0px; fill-opacity: 1.0} .element.point:hover {fill: #95fce8; stroke-width: 5px; stroke: #95fce8} ')  + guide(y:t) style('stroke: #dfdfdf')

**Comment by grahamwills** [comment] 2016-08-30 21:37
I could not reproduce this, but it seems very likely to be a numeric round-off issue. I have checked in a guard for that, but if it does not solve the issue, please re-open this defect

**Closed by grahamwills** 2016-08-30 21:37 UTC
Labels: bug
