### ISSUE TITLE
Panning moves graph elements outside of the graph frame

### ISSUE THREAD

**Issue by dpierucci** [Brunel-Visualization/Brunel#114] opened 2016-06-29 16:35 UTC
In the latest build of Brunel on the develop branch, when I pan to move points to the left or down, the points are visible outside of the graph frame. Please see image in attached file.

![panningissue](https://cloud.githubusercontent.com/assets/19497430/16460552/84b52f2e-3ded-11e6-95bc-de546a27d5e8.png)

**Comment by grahamwills** [comment] 2016-06-29 21:04
I'm having difficulty replicating this on the develop branch; can you paste the Brunel into the comments section so I can get a better idea?

**Comment by dpierucci** [comment] 2016-06-29 22:11
point x(Predicted) y(Observed) size(Frequency:[100, 800])  tooltip(#all) style('.element.point {stroke-width: 0px; fill-opacity: 0.25} ')  + point x(Predicted) y(Observed) style('stroke-width: 0px; fill-opacity: 1.0') tooltip("Predicted: ", Predicted, "<br>Observed:", Observed, "<br>Frequency:", Frequency) title("Size = frequency":footer) effect(enter) axes(x:grid, y:grid) style('.inner {stroke:#e0e0e0; stroke-width:1px} .axis {label-location:left} .grid{opacity:1}   .grid.x {stroke:#777677; stroke-dasharray:2,2} .grid.y {stroke:#777677; stroke-dasharray:2,2}')

**Comment by grahamwills** [comment] 2016-06-30 15:41
[version with the US data]

point x(winter) y(summer) size(population:[100, 800]) tooltip(#all) style('.element.point {stroke-width: 0px; fill-opacity: 0.25} ') + point x(winter) y(summer) tooltip('Predicted: ', winter, '
Observed:', summer, '
Frequency:', population) axes(x:grid, y:grid) style('stroke-width: 0px; fill-opacity: 1.0') style('.inner {stroke:#e0e0e0; stroke-width:1px} .axis {label-location:left} .grid{opacity:1} .grid.x {stroke:#777677; stroke-dasharray:2,2} .grid.y {stroke:#777677; stroke-dasharray:2,2}') effect(enter) title('Size = frequency':footer)

**Comment by grahamwills** [comment] 2016-06-30 15:43
Hmmm. cannot reproduce on a mac in Safari, FF, or Chrome -- the mechanism for doing this is a clip path which seems to be in good order. I may need to get the actual HTML file to see what's going on.

**Comment by danrope** [comment] 2016-08-19 13:30
Related? When I run latest Brunel Test (2.0 test 3) using the following:

`data('sample:US States.csv') bar x(State) y(Rain) mean(Rain) sort(Rain) interaction(panzoom:x) transpose`,

The axes labels are visible when they are panned outside the graph region.

**Comment by grahamwills** [comment] 2016-08-19 14:24
Sadly not -- the axis clip region is different from the chart one. But 
I'll fix it anyway




Graham Wills
STSM, Analytics and Data Science
IBM Watson Analytics
work:
gwills@us.ibm.com
personal:
graham@willsfamily.org
blog:
workingvis.com

**Comment by grahamwills** [comment] 2016-08-19 14:55
From the related info, I think I have tracked down the issue. I have checked in a fix that should resolve it, but cannot replicate the error still. Will mark as fixed, but please re-open if the fix didn't work

**Closed** 2016-08-19 14:55 UTC
Labels: bug, help wanted
